### ISSUE TITLE
Typo: the-algorithm.md

### ISSUE THREAD

**Issue by joshoua** [Peter-Ebert/Valli-Encoding#2]
At symbol 'd' in Decoding Example:

![image](https://github.com/user-attachments/assets/90230f05-bcbe-4215-b8a4-684205697225)

If I'm not mistaken, this should say `6 choose 2 == 15`. This caused some confusion while reading the rest of the block.

**Comment by Peter-Ebert** [comment]
Yes good catch!  6 choose 2 matches the values above and below.  Give me a minute to update.

**Comment by Peter-Ebert** [comment]
Updated, let me know if you see anything else.  Thanks
